using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace genshin_gotcha
{
    class Data
    {
        public static Dictionary<string, Character> ch = new Dictionary<string, Character>()
        {
            ["diluc"] = new Character("다이루크", 5, "남성", "몬드", 0430, "불", "양손검"),
            ["mona"] = new Character("모나", 5, "여성", "몬드", 0831, "물", "법구"),
            ["jean"] = new Character("진", 5, "여성", "몬드", 0314, "바람", "한손검"),
            ["qiqi"] = new Character("치치", 5, "여성", "리월", 0303, "얼음", "한손검"),
            ["keqing"] = new Character("각청", 5, "여성", "리월", 1120, "번개", "한손검"),
            ["tighnari"] = new Character("타이나리", 5, "남성", "수메르", 1229, "풀", "활"),

            ["venti"] = new Character("벤티", 5, "남성", "몬드", 0616, "바람", "활"),
            ["klee"] = new Character("클레", 5, "여성", "몬드", 0727, "불", "법구"),
            ["tartaglia"] = new Character("타르탈리아", 5, "남성", "스네즈나야", 0720, "물", "활"),
            ["zhongli"] = new Character("종려", 5, "남성", "리월", 1231, "바위", "장병기"),
            ["albedo"] = new Character("알베도", 5, "남성", "몬드", 0913, "바위", "한손검"),
            ["ganyu"] = new Character("감우", 5, "여성", "리월", 1202, "얼음", "활"),
            ["xiao"] = new Character("소", 5, "남성", "리월", 0417, "바람", "장병기"),
            ["hutao"] = new Character("호두", 5, "여성", "리월", 0715, "불", "장병기"),
            ["eula"] = new Character("유라", 5, "여성", "몬드", 1025, "얼음", "양손검"),
            ["kazuha"] = new Character("카에데하라 카즈하", 5, "남성", "이나즈마", 1029, "바람", "한손검"),
            ["ayaka"] = new Character("카미사토 아야카", 5, "여성", "이나즈마", 0928, "얼음", "한손검"),
            ["yoimiya"] = new Character("요이미야", 5, "여성", "이나즈마", 0621, "불", "활"),
            ["raiden"] = new Character("라이덴 쇼군", 5, "여성", "이나즈마", 0626, "번개", "장병기"),
            ["kokomi"] = new Character("산고노미야 코코미", 5, "여성", "이나즈마", 0222, "물", "법구"),
            ["itto"] = new Character("아라타키 이토", 5, "남성", "이나즈마", 0601, "바위", "양손검"),
            ["shenhe"] = new Character("신학", 5, "여성", "리월", 0310, "얼음", "장병기"),
            ["miko"] = new Character("야에 미코", 5, "여성", "이나즈마", 0627, "번개", "법구"),
            ["ayato"] = new Character("카미사토 아야토", 5, "남성", "이나즈마", 0326, "물", "한손검"),
            ["yelan"] = new Character("야란", 5, "여성", "리월", 0420, "물", "활"),
            ["cyno"] = new Character("사이노", 5, "남성", "수메르", 0623, "번개", "장병기"),

            ["amber"] = new Character("엠버", 4, "여성", "몬드", 0810, "불", "활"),
            ["kaeya"] = new Character("케이아", 4, "남성", "몬드", 1130, "얼음", "한손검"),
            ["lisa"] = new Character("리사", 4, "여성", "몬드", 0609, "번개", "법구"),
            ["barbara"] = new Character("바바라", 4, "여성", "몬드", 0229, "물", "법구"),
            ["fischl"] = new Character("피슬", 4, "여성", "몬드", 0527, "번개", "활"),
            ["xiangling"] = new Character("향릉", 4, "여성", "리월", 1102, "불", "장병기"),
            ["xingqiu"] = new Character("행추", 4, "남성", "리월", 1009, "물", "한손검"),
            ["noelle"] = new Character("노엘", 4, "여성", "몬드", 0321, "바위", "양손검"),
            ["sucrose"] = new Character("설탕", 4, "여성", "몬드", 1126, "바람", "법구"),
            ["beidou"] = new Character("북두", 4, "여성", "리월", 0214, "번개", "양손검"),
            ["ningguang"] = new Character("응광", 4, "여성", "리월", 0826, "바위", "법구"),
            ["razor"] = new Character("레이저", 4, "남성", "몬드", 0909, "번개", "양손검"),
            ["chongyun"] = new Character("증운", 4, "남성", "리월", 0907, "얼음", "양손검"),
            ["bennett"] = new Character("베넷", 4, "남성", "몬드", 0229, "불", "한손검"),

            ["diona"] = new Character("디오나", 4, "여성", "몬드", 0229, "얼음", "활"),
            ["xinyan"] = new Character("신염", 4, "여성", "리월", 1016, "불", "양손검"),
            ["rosaria"] = new Character("로자리아", 4, "여성", "몬드", 0124, "얼음", "장병기"),
            ["yanfei"] = new Character("연비", 4, "여성", "리월", 0728, "불", "법구"),
            ["sayu"] = new Character("사유", 4, "여성", "이나즈마", 1019, "바람", "양손검"),
            ["sara"] = new Character("쿠죠 사라", 4, "여성", "이나즈마", 0714, "번개", "활"),
            ["thoma"] = new Character("토마", 4, "남성", "이나즈마", 0109, "불", "장병기"),
            ["gorou"] = new Character("고로", 4, "남성", "이나즈마", 0518, "바위", "활"),
            ["yunjin"] = new Character("운근", 4, "여성", "리월", 0521, "바위", "장병기"),
            ["shinobu"] = new Character("쿠키 시노부", 4, "여성", "이나즈마", 0727, "번개", "한손검"),
            ["heizou"] = new Character("시카노인 헤이조", 4, "남성", "이나즈마", 0724, "바람", "법구"),
            ["collei"] = new Character("콜레이", 4, "여성", "수메르", 0508, "풀", "활"),
            ["dori"] = new Character("도리", 4, "여성", "수메르", 1221, "번개", "양손검"),
            ["candace"] = new Character("캔디스", 4, "여성", "수메르", 0503, "물", "장병기"),
        };
        public static Dictionary<string, Weapon> wp = new Dictionary<string, Weapon>()
        {
            ["aquila_favonia"] = new Weapon("매의 검", 5, "한손검"),
            ["skyward_blade"] = new Weapon("천공의 검", 5, "한손검"),
            ["summit_shaper"] = new Weapon("참봉의 칼날", 5, "한손검"),
            ["primordial_jade_cutter"] = new Weapon("반암결록", 5, "한손검"),
            ["freedom_sworn"] = new Weapon("오래된 자유의 서약", 5, "한손검"),
            ["mistsplitter_reforged"] = new Weapon("안개를 가르는 회광", 5, "한손검"),
            ["haran_geppaku_futsu"] = new Weapon("하란 월백의 후츠", 5, "한손검"),
            ["key_of_khaj_nisut"] = new Weapon("성현의 열쇠", 5, "한손검"),
            ["favonius_sword"] = new Weapon("페보니우스 검", 4, "한손검"),
            ["the_flute"] = new Weapon("피리검", 4, "한손검"),
            ["sacrificial_sword"] = new Weapon("제례검", 4, "한손검"),
            ["lion's_roar"] = new Weapon("용의 포효", 4, "한손검"),
            ["the_alley_flash"] = new Weapon("뒷골목의 섬광", 4, "한손검"),
            ["xiphos'_moonlight"] = new Weapon("크시포스의 달빛", 4, "한손검"),
            ["cool_steel"] = new Weapon("차가운 칼날", 3, "한손검"),
            ["harbinger_of_dawn"] = new Weapon("여명신검", 3, "한손검"),
            ["skyrider_sword"] = new Weapon("비천어검", 3, "한손검"),
            
            ["skyward_pride"] = new Weapon("천공의 긍지", 5, "양손검"),
            ["wolf's_gravestone"] = new Weapon("늑대의 말로", 5, "양손검"),
            ["the_unforged"] = new Weapon("무공의 검", 5, "양손검"),
            ["song_of_broken_pines"] = new Weapon("송뢰가 울릴 무렵", 5, "양손검"),
            ["redhorn_stonethresher"] = new Weapon("쇄석의 붉은 뿔", 5, "양손검"),
            ["fevonius_greatsword"] = new Weapon("페보니우스 대검", 4, "양손검"),
            ["the_bell"] = new Weapon("시간의 검", 4, "양손검"),
            ["sacrificial_greatsword"] = new Weapon("제례 대검", 4, "양손검"),
            ["rainslasher"] = new Weapon("빗물 베기", 4, "양손검"),
            ["lithic_blade"] = new Weapon("천암고검", 4, "양손검"),
            ["akuoumaru"] = new Weapon("아쿠오마루", 4, "양손검"),
            ["makhaira_aquamarine"] = new Weapon("물빛 마카이라", 4, "양손검"),
            ["ferrous_shadow"] = new Weapon("강철의 그림자", 3, "양손검"),
            ["bloodtainted_greatsword"] = new Weapon("드래곤 블러드 소드", 3, "양손검"),
            ["debate_club"] = new Weapon("훌륭한 대화수단", 3, "양손검"),

            ["primordial_jade_winged_spear"] = new Weapon("화박연", 5, "장병기"),
            ["skyward_spine"] = new Weapon("천공의 마루", 5, "장병기"),
            ["vortex_vanquisher"] = new Weapon("관홍의 창", 5, "장병기"),
            ["staff_of_homa"] = new Weapon("호마의 지팡이", 5, "장병기"),
            ["engulfing_lightning"] = new Weapon("예초의 번개", 5, "장병기"),
            ["calamity_queller"] = new Weapon("식재", 5, "장병기"),
            ["staff_of_the_scarlet_sands"] = new Weapon("적색 사막의 지팡이", 5, "장병기"),
            ["dragon's_bane"] = new Weapon("용학살창", 4, "장병기"),
            ["favonius_lance"] = new Weapon("페보니우스 장창", 4, "장병기"),
            ["lithic_spear"] = new Weapon("천암장창", 4, "장병기"),
            ["wavebreaker's_fin"] = new Weapon("파도 베는 지느러미", 4, "장병기"),
            ["black_tassel"] = new Weapon("흑술창", 3, "장병기"),

            ["skyward_atlas"] = new Weapon("천공의 두루마리", 5, "법구"),
            ["lost_prayer_to_the_sacred_winds"] = new Weapon("사풍 원서", 5, "법구"),
            ["memory_of_dust"] = new Weapon("속세의 자물쇠", 5, "법구"),
            ["everlasting_moonglow"] = new Weapon("불멸의 달빛", 5, "법구"),
            ["kagura's_verity"] = new Weapon("카구라의 진의", 5, "법구"),
            ["favonius_codex"] = new Weapon("페보니우스 비전", 4, "법구"),
            ["the_widsith"] = new Weapon("음유시인의 악장", 4, "법구"),
            ["sacrificial_fragments"] = new Weapon("제례의 악장", 4, "법구"),
            ["eye_of_perception"] = new Weapon("소심", 4, "법구"),
            ["wine_and_song"] = new Weapon("뒷골목의 술과 시", 4, "법구"),
            ["wandering_evenstar"] = new Weapon("방랑하는 저녁별", 4, "법구"),
            ["magic guide"] = new Weapon("마도 서론", 3, "법구"),
            ["thrilling_tales_of_dragon_slayers"] = new Weapon("드래곤 슬레이어 영웅담", 3, "법구"),
            ["emerald_orb"] = new Weapon("비취 오브", 3, "법구"),

            ["skyward_harp"] = new Weapon("천공의 날개", 5, "활"),
            ["amos'_bow"] = new Weapon("아모스의 활", 5, "활"),
            ["elegy_for_the_end"] = new Weapon("종말 탄식의 노래", 5, "활"),
            ["thundering_pulse"] = new Weapon("비뢰의 고동", 5, "활"),
            ["polar_star"] = new Weapon("극지의 별", 5, "활"),
            ["aqua_simulacra"] = new Weapon("약수", 5, "활"),
            ["hunter's_path"] = new Weapon("사냥꾼의 길", 5, "활"),
            ["favonius_warbow"] = new Weapon("페보니우스 활", 4, "활"),
            ["the_stringless"] = new Weapon("절현", 4, "활"),
            ["sacrificial_bow"] = new Weapon("제례활", 4, "활"),
            ["rust"] = new Weapon("녹슨 활", 4, "활"),
            ["alley_hunter"] = new Weapon("뒷골목 사냥꾼", 4, "활"),
            ["mitternachts_waltz"] = new Weapon("유야의 왈츠", 4, "활"),
            ["mouun's_moon"] = new Weapon("모운의 달", 4, "활"),
            ["raven_bow"] = new Weapon("까마귀깃 활", 3, "활"),
            ["sharpshooter's_oath"] = new Weapon("신궁의 서약", 3, "활"),
            ["slingshot"] = new Weapon("탄궁", 3, "활"),
        };
        public static Dictionary<string, Randombox> rb = new Dictionary<string, Randombox>()
        {
            ["alwase"] = new Randombox("세상 여행", 
                new List<string> { "diluc", "mona", "jean", "qiqi", "keqing", "tighnari" }, 
                new List<string> 
                {
                    "amber", "kaeya", "lisa", "barbara", "fischl", "xiangling", "xingqiu",
                    "noelle", "sucrose", "beidou", "ningguang", "razor", "chongyun", "bennett",
                    "diona",  "xinyan", "rosaria", "yanfei", "sayu", "sara", "thoma", "gorou",
                    "yunjin", "shinobu", "heizou", "collei", "dori", "candace"
                },
                new List<string>
                {
                    "aquila_favonia", "skyward_blade", "wolf's_gravestone", "skyward_pride",
                    "lost_prayer_to_the_sacred_winds", "skyward_atlas", "primordial_jade_winged_spear",
                    "skyward_spine", "amos'_bow", "skyward_harp"
                },
                new List<string>
                {
                    "favonius_sword", "sacrificial_sword", "the_flute", "lion's_roar",
                    "fevonius_greatsword", "sacrificial_greatsword", "the_bell", "rainslasher",
                    "favonius_codex", "sacrificial_fragments", "the_widsith", "eye_of_perception",
                    "favonius_lance", "dragon's_bane", "favonius_warbow", "sacrificial_bow",
                    "the_stringless", "rust"
                },
                new List<string>
                {
                    "cool_steel", "harbinger_of_dawn", "skyrider_sword", "ferrous_shadow",
                    "bloodtainted_greatsword", "debate_club", "black_tassel", "magic guide",
                    "thrilling_tales_of_dragon_slayers", "emerald_orb", "raven_bow",
                    "sharpshooter's_oath", "slingshot"
                }
            ),
            ["venti_1"] = new Randombox("잔에 담긴 시", new List<string> { "venti" }, new List<string> { "barbara", "fischl", "xiangling" }, 4, 14),
            ["klee_1"] = new Randombox("번쩍이는 화염", new List<string> { "klee" }, new List<string> { "xingqiu", "noelle", "sucrose" }, 4, 14),
            ["tartaglia_1"] = new Randombox("겨울 나라와의 이별", new List<string> { "tartaglia" }, new List<string> { "diona", "beidou", "ningguang" }, 4, 14),
            ["zhongli_1"] = new Randombox("산야의 시조", new List<string> { "zhongli" }, new List<string> { "xinyan", "razor", "chongyun" }, 4, 15),
            ["albedo_1"] = new Randombox("심비의 숨결", new List<string> { "albedo" }, new List<string> { "fischl", "sucrose", "bennett" }, 4, 16),
            ["ganyu_1"] = new Randombox("덧없는 인생", new List<string> { "ganyu" }, new List<string> { "xiangling", "xingqiu", "noelle" }, 4, 16),
            ["xiao_1"] = new Randombox("등불의 초대", new List<string> { "xiao" }, new List<string> { "diona", "beidou", "xinyan" }, 4, 16),
            ["keqing_1"] = new Randombox("용등의 춤", new List<string> { "keqing" }, new List<string> { "ningguang", "bennett", "barbara" }, 4, 16),
            ["hutao_1"] = new Randombox("매화가 만개할 때", new List<string> { "hutao" }, new List<string> { "xingqiu", "xiangling", "chongyun" }, 4, 16),
            ["venti_2"] = new Randombox("잔에 담긴 시", new List<string> { "venti" }, new List<string> { "sucrose", "razor", "noelle" }, 5, 15),
            ["tartaglia_2"] = new Randombox("겨울 나라와의 이별", new List<string> { "tartaglia" }, new List<string> { "rosaria", "barbara", "fischl" }, 5, 16),
            ["zhongli_2"] = new Randombox("산야의 시조", new List<string> { "zhongli" }, new List<string> { "yanfei", "noelle", "diona" }, 5, 17),
            ["eula_1"] = new Randombox("파도가 치는 순간", new List<string> { "eula" }, new List<string> { "xinyan", "xingqiu", "beidou" }, 5, 18),
            ["klee_2"] = new Randombox("번쩍이는 화염", new List<string> { "klee" }, new List<string> { "barbara", "sucrose", "fischl" }, 5, 18),
            ["kazuha_1"] = new Randombox("바람에 지는 낙엽", new List<string> { "kazuha" }, new List<string> { "bennett", "sucrose", "razor" }, 5, 18),
            ["ayaka_1"] = new Randombox("백로의 정원", new List<string> { "ayaka" }, new List<string> { "ningguang", "chongyun", "yanfei" }, 5, 18),
            ["yoimiya_1"] = new Randombox("은하수를 물들인 불꽃", new List<string> { "yoimiya" }, new List<string> { "sayu", "diona", "xinyan" }, 5, 18),
            ["raiden_1"] = new Randombox("정토 좇는 천하인", new List<string> { "raiden" }, new List<string> { "sara", "xiangling", "sucrose" }, 5, 19),
            ["kokomi_1"] = new Randombox("산악에 뜬 구슬", new List<string> { "kokomi" }, new List<string> { "rosaria", "beidou", "xingqiu" }, 5, 20),
            ["tartaglia_3"] = new Randombox("겨울 나라와의 이별", new List<string> { "tartaglia" }, new List<string> { "ningguang", "chongyun", "yanfei" }, 5, 20),
            ["hutao_2"] = new Randombox("매화가 만개할 때", new List<string> { "hutao" }, new List<string> { "thoma", "diona", "sayu" }, 5, 20),
            ["albedo_2"] = new Randombox("심비의 숨결", new List<string> { "albedo" }, new List<string> { "bennett", "noelle", "rosaria" }, 5, 21),
            ["eula_2"] = new Randombox("파도가 치는 순간", new List<string> { "eula" }, new List<string> { "bennett", "noelle", "rosaria" }, 5, 21),
            ["itto_1"] = new Randombox("귀문투연", new List<string> { "itto" }, new List<string> { "gorou", "barbara", "xiangling" }, 5, 21),
            ["shenhe_1"] = new Randombox("속세의 귀객", new List<string> { "shenhe" }, new List<string> { "yunjin", "ningguang", "chongyun" }, 5, 22),
            ["xiao_2"] = new Randombox("등불의 초대", new List<string> { "xiao" }, new List<string> { "yunjin", "ningguang", "chongyun" }, 5, 22),
            ["zhongli_3"] = new Randombox("산야의 시조", new List<string> { "zhongli" }, new List<string> { "xingqiu", "beidou", "yanfei" }, 5, 23),
            ["ganyu_2"] = new Randombox("덧없는 인생", new List<string> { "ganyu" }, new List<string> { "xingqiu", "beidou", "yanfei" }, 5, 23),
            ["miko_1"] = new Randombox("자홍의 벚꽃", new List<string> { "miko" }, new List<string> { "fischl", "diona", "thoma" }, 5, 23),
            ["raiden_2"] = new Randombox("정토 좇는 천하인", new List<string> { "raiden" }, new List<string> { "bennett", "xinyan", "sara" }, 5, 23),
            ["kokomi_2"] = new Randombox("산악에 뜬 구슬", new List<string> { "kokomi" }, new List<string> { "bennett", "xinyan", "sara" }, 5, 23),
            ["ayato_1"] = new Randombox("푸른 물결 속 가벼운 걸음", new List<string> { "ayato" }, new List<string> { "sucrose", "xiangling", "yunjin" }, 5, 23),
            ["venti_3"] = new Randombox("잔에 담긴 시", new List<string> { "venti" }, new List<string> { "sucrose", "xiangling", "yunjin" }, 5, 23),
            ["ayaka_2"] = new Randombox("백로의 정원", new List<string> { "ayaka" }, new List<string> { "razor", "rosaria", "sayu" }, 5, 23),
            ["yelan_1"] = new Randombox("하늘을 정탐하는 백홍", new List<string> { "yelan" }, new List<string> { "barbara", "yanfei", "noelle" }, 5, 23),
            ["xiao_3"] = new Randombox("등불의 초대", new List<string> { "xiao" }, new List<string> { "barbara", "yanfei", "noelle" }, 5, 23),
            ["itto_2"] = new Randombox("귀문투연", new List<string> { "itto" }, new List<string> { "shinobu", "chongyun", "gorou" }, 5, 23),
            ["kazuha_2"] = new Randombox("바람에 지는 낙엽", new List<string> { "kazuha" }, new List<string> { "heizou", "ningguang", "thoma" }, 5, 24),
            ["klee_3"] = new Randombox("번쩍이는 화염", new List<string> { "klee" }, new List<string> { "heizou", "ningguang", "thoma" }, 5, 24),
            ["yoimiya_2"] = new Randombox("은하수를 물들인 불꽃", new List<string> { "yoimiya" }, new List<string> { "bennett", "xinyan", "yunjin" }, 5, 25),
            ["tighnari_1"] = new Randombox("숲속 순회", new List<string> { "tighnari" }, new List<string> { "collei", "diona", "fischl" }, 5, 25),
            ["zhongli_4"] = new Randombox("산야의 시조", new List<string> { "zhongli" }, new List<string> { "collei", "diona", "fischl" }, 5, 25),
            ["ganyu_3"] = new Randombox("덧없는 인생", new List<string> { "ganyu" }, new List<string> { "dori", "sucrose", "xingqiu" }, 5, 26),
            ["kokomi_3"] = new Randombox("산악에 뜬 구슬", new List<string> { "kokomi" }, new List<string> { "dori", "sucrose", "xingqiu" }, 5, 26),
            ["cyno_1"] = new Randombox("황혼을 가르는 번개의 심판", new List<string> { "cyno" }, new List<string> { "candace", "shinobu", "sayu" }, 6, 27),
            ["venti_4"] = new Randombox("잔에 담긴 시", new List<string> { "venti" }, new List<string> { "candace", "shinobu", "sayu" }, 6, 27),
        };
    }
}
